export const ASP_ERROR_CODES = {
  PARSE_ERROR: 'PARSE_ERROR',
  POLICY_VALIDATION_ERROR: 'POLICY_VALIDATION_ERROR',
  EVENT_VALIDATION_ERROR: 'EVENT_VALIDATION_ERROR',
  EVALUATION_ERROR: 'EVALUATION_ERROR',
  INVARIANT_VIOLATION: 'INVARIANT_VIOLATION',
} as const;

export type AspErrorCode = (typeof ASP_ERROR_CODES)[keyof typeof ASP_ERROR_CODES];
