export const ASP_ERROR_CODES = {
  PARSE_ERROR: 'PARSE_ERROR',
  POLICY_COMPILATION_ERROR: 'POLICY_COMPILATION_ERROR',
  POLICY_VALIDATION_ERROR: 'POLICY_VALIDATION_ERROR',
  EVENT_VALIDATION_ERROR: 'EVENT_VALIDATION_ERROR',
  TRACE_VALIDATION_ERROR: 'TRACE_VALIDATION_ERROR',
  TESTCASE_VALIDATION_ERROR: 'TESTCASE_VALIDATION_ERROR',
  EVALUATION_ERROR: 'EVALUATION_ERROR',
  REPLAY_ERROR: 'REPLAY_ERROR',
  TEST_RUNNER_ERROR: 'TEST_RUNNER_ERROR',
  INVARIANT_VIOLATION: 'INVARIANT_VIOLATION',
} as const;

export type AspErrorCode = (typeof ASP_ERROR_CODES)[keyof typeof ASP_ERROR_CODES];
